{
  description = "<Put your description here>";

  inputs.clan-core.url = "https://git.clan.lol/clan/clan-core/archive/main.tar.gz";
  inputs.nixpkgs.follows = "clan-core/nixpkgs";
  inputs.flake-parts.url = "github:hercules-ci/flake-parts";
  inputs.flake-parts.inputs.nixpkgs-lib.follows = "nixpkgs";
  inputs.treefmt-nix.url = "github:numtide/treefmt-nix";
  inputs.treefmt-nix.inputs.nixpkgs.follows = "nixpkgs";


  outputs =
    inputs@{
      self,
      clan-core,
      nixpkgs,
      flake-parts,
      ...
    }:
    flake-parts.lib.mkFlake { inherit inputs; } ({
      systems = [
        "x86_64-linux"
        "aarch64-linux"
        "x86_64-darwin"
        "aarch64-darwin"
      ];
      imports = [ inputs.clan-core.flakeModules.default  ./treefmt.nix ];


      # https://docs.clan.lol/getting-started/flake-parts/
      clan = {
        meta.name = "vpnBenchClan"; # Ensure this is unique among all clans you want to use.

        pkgsForSystem = system: import nixpkgs {
            inherit system;
            config.allowUnfree = true;
          };

        # Make flake available in modules
        specialArgs.self = {
          inherit (self) inputs nixosModules packages;
        };
        directory = self;
        machines = {
          # "jon" will be the hostname of the machine
          jon =
            { pkgs, ... }:
            {
              imports = [
                ./modules/shared.nix
                ./modules/disko.nix
                ./machines/jon/configuration.nix
              ];

              clan.core.networking.targetHost = pkgs.lib.mkDefault "lhebendanz@34.150.73.228";
  

              clan.core.networking.zerotier.controller.enable = true;
            };
          # "sara" will be the hostname of the machine
          sara =
            { pkgs, ... }:
            {
              imports = [
                ./modules/shared.nix
                ./modules/disko.nix
                ./machines/sara/configuration.nix
              ];

              # Set this for clan commands use ssh i.e. `clan machines update`
              # If you change the hostname, you need to update this line to root@<new-hostname>
              # This only works however if you have avahi running on your admin machine else use IP
              clan.core.networking.targetHost = pkgs.lib.mkDefault "root@sara";

              /*
                After jon is deployed, uncomment the following line
                This will allow sara to share the VPN overlay network with jon
                The networkId is generated by the first deployment of jon
              */
              # clan.core.networking.zerotier.networkId = builtins.readFile ../jon/facts/zerotier-network-id;
            };
        };
      };
      perSystem =
        { pkgs, inputs', system, ... }:#
        let
          clan-cli = inputs'.clan-core.packages.clan-cli;
          
        in 
        {
          _module.args.pkgs = import nixpkgs {
            inherit system;
            config.allowUnfree = true;
          };
          
          devShells.default = pkgs.callPackage ./shell.nix { inherit clan-cli;};
        };
    });
}
