import { onMount, JSX } from "solid-js";

interface LlmDisclaimerProps {
  id: string;
  title?: string;
  children: JSX.Element;
}

// Helper to check if disclaimer should be open (reads localStorage synchronously)
const shouldBeOpen = (id: string): boolean => {
  try {
    const key = `llm-disclaimer-${id}-collapsed`;
    return localStorage.getItem(key) !== "true";
  } catch {
    return true;
  }
};

export const LlmDisclaimer = (props: LlmDisclaimerProps) => {
  let detailsRef: HTMLDetailsElement | undefined;
  const storageKey = `llm-disclaimer-${props.id}-collapsed`;

  // Compute initial state synchronously before render
  const initialOpen = shouldBeOpen(props.id);

  onMount(() => {
    if (!detailsRef) return;

    // Listen for toggle events to persist state
    detailsRef.addEventListener("toggle", () => {
      localStorage.setItem(storageKey, (!detailsRef!.open).toString());
    });
  });

  return (
    <details
      ref={detailsRef}
      {...(initialOpen ? { open: true } : {})}
      style={{
        "margin-bottom": "1.5rem",
        padding: "1rem",
        background: "#fef3c7",
        border: "1px solid #f59e0b",
        "border-radius": "0.5rem",
      }}
    >
      <summary
        style={{
          cursor: "pointer",
          "font-weight": "600",
          color: "#92400e",
        }}
      >
        {props.title ?? "LLM-Generated Content"} (click to collapse)
      </summary>
      <div style={{ "margin-top": "0.75rem", color: "#78350f" }}>
        {props.children}
      </div>
    </details>
  );
};

export const FeatureMatrixDisclaimer = () => (
  <LlmDisclaimer id="feature-matrix">
    <p>
      This feature matrix has been fully generated by an LLM by cloning the VPN
      source repositories and analyzing them with specific instructions.
    </p>
    <p>
      <strong>LLM Instructions Used:</strong>
    </p>
    <ul style={{ "margin-left": "1.5rem", "list-style-type": "disc" }}>
      <li>
        <a
          href="/llm-instructions?file=overview"
          style={{ color: "#d97706", "text-decoration": "underline" }}
        >
          2026-01-13-init-overview-md.txt
        </a>{" "}
        (for overview files)
      </li>
      <li>
        <a
          href="/llm-instructions?file=analysis"
          style={{ color: "#d97706", "text-decoration": "underline" }}
        >
          2026-01-13-init-analysis-md.txt
        </a>{" "}
        (for initial analysis)
      </li>
    </ul>
    <p>
      <strong>Found an inaccuracy?</strong> PRs are welcome at the{" "}
      <a
        href="https://git.clan.lol/Qubasa/vpn-benchmark/src/branch/main/pkgs/webview-ui/app/analysis"
        style={{ color: "#d97706", "text-decoration": "underline" }}
      >
        analysis repository
      </a>
      .
    </p>
  </LlmDisclaimer>
);

export const OverviewDisclaimer = () => (
  <LlmDisclaimer id="overview">
    <p>
      This overview has been fully generated by an LLM by cloning the VPN source
      repositories and analyzing them with specific instructions.
    </p>
    <p>
      <strong>LLM Instructions Used:</strong>
    </p>
    <ul style={{ "margin-left": "1.5rem", "list-style-type": "disc" }}>
      <li>
        <a
          href="/llm-instructions?file=overview"
          style={{ color: "#d97706", "text-decoration": "underline" }}
        >
          2026-01-13-init-overview-md.txt
        </a>
      </li>
    </ul>
    <p>
      <strong>Found an inaccuracy?</strong> PRs are welcome at the{" "}
      <a
        href="https://git.clan.lol/Qubasa/vpn-benchmark/src/branch/main/pkgs/webview-ui/app/analysis"
        style={{ color: "#d97706", "text-decoration": "underline" }}
      >
        analysis repository
      </a>
      .
    </p>
  </LlmDisclaimer>
);
